name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_flutter_versions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flutter: [ '3.24.0', '3.27.0', '3.29.0', '3.32.0', 'stable' ]
    name: Tests on Flutter ${{ matrix.flutter }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter }}

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        
      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

  test_os_matrix:
    needs: test_flutter_versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: Tests on ${{ matrix.os }} (stable)
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
