name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_flutter_versions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flutter: [ '3.24.0', '3.27.0', '3.29.0', '3.32.0', 'stable', 'beta' ]
    name: Tests on Flutter ${{ matrix.flutter }}
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        if: matrix.flutter == 'stable' || matrix.flutter == 'beta'
        with:
          channel: ${{ matrix.flutter }}

      - uses: subosito/flutter-action@v2
        if: matrix.flutter != 'stable' && matrix.flutter != 'beta'
        with:
          flutter-version: ${{ matrix.flutter }}

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        
      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

  test_os_matrix:
    needs: test_flutter_versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: Tests & Builds on ${{ matrix.os }} (channel stable)
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      # Linux build (example app)
      - name: Install Linux desktop dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Enable Linux desktop
        if: matrix.os == 'ubuntu-latest'
        run: flutter config --enable-linux-desktop

      - name: Build Linux example
        if: matrix.os == 'ubuntu-latest'
        working-directory: example
        run: |
          flutter pub get
          flutter build linux

      # Windows build (example app)
      - name: Enable Windows desktop
        if: matrix.os == 'windows-latest'
        run: flutter config --enable-windows-desktop

      - name: Build Windows example
        if: matrix.os == 'windows-latest'
        working-directory: example
        run: |
          flutter pub get
          flutter build windows

      # macOS build (example app)
      - name: Enable macOS desktop
        if: matrix.os == 'macos-latest'
        run: flutter config --enable-macos-desktop

      - name: Build macOS example
        if: matrix.os == 'macos-latest'
        working-directory: example
        run: |
          flutter pub get
          flutter build macos
